version: '3'

services:

  addtonotionbot:
    # depends_on:
    #   - imgpush
    build: .
    container_name: addtonotionbot
    restart: always
    volumes:
      - ".env:/app/.env"
      - "./storage:/app/storage"